image: node:latest
stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: eu-central-1
  BUCKET_NAME: dev.tafelhilfe.de

cache:
  paths:
    - vendor
    
job:
    only:
        - /dev

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploys3:
  image: "python:latest"
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install awscli
  script:
    - aws s3 cp dist s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}
    on_stop: clean_s3

clean_s3:
  image: "python:latest"
  stage: deploy
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
