name: Deploy Development

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: npm install
      
    - name: Build Assets
      run: npm run generate

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
        
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: "Deploy to S§"
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-1" 
          SOURCE_DIR: "dist"
